#cloud-config
users:
  - name: ${ssh_username}
    ssh-authorized-keys:
      - ${public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - wget
  - ntpdate
